export const DEPART_HTA_OPTIONS = [
  'Oualidia - Rural',
  'Oualidia - Zemamra',
  'Oualidia - Centre',
  'Oualidia - Beddouza',
  'Oualidia - Moul lbergui',
  'Sidi bennou - Sidi Smail',
  'Sidi bennour - Centre 1',
  'Sidi bennour - Centre 2',
  'Sidi bennour - Laaounate',
  'Sidi bennour - RTM',
  'Sidi bennour - Bir Laabid',
  'Sidi bennour - Od amrane',
  'Sidi bennour - Od frej',
  'Sidi bennour - Sucrerie',
  'Sidi bennour - Zemamra',
  'Sidi bennour - Khmis ksiba',
  'Youssoufia -Hormat ALLH',
  'Zemamra - Centre',
  'Zemamra - Z1Z2',
  'Zemamra - Z0',
  'Zemamra - Z3',
  'Zemamra - Elgharbia',
  'Zemamra - Sebt sais',
  'Zemamra - Sidi bennour',
  'Zemamra - Elgharbia',
  'Zemamra - Oualidia',
  'Zemamra - Sucrerie',
] as const;

export type DepartHta = typeof DEPART_HTA_OPTIONS[number];
